import { Room, FAQItem } from './types';

export const ROOMS: Room[] = [
  {
    id: '1',
    title: 'Habitación acogedora cerca del Tecno',
    location: 'Barrio Norte, 450m del campus',
    price: 500,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=500&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop',
    ],
    type: 'private',
    amenities: ['Baño privado', 'WiFi rápido', 'Cocina completa', 'Aire acondicionado'],
    badges: ['Verificado', 'Cerca del campus', 'Solo estudiantes'],
    verified: true,
    host: {
      id: 'h1',
      name: 'María Rodríguez',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
      bio: 'Anfitriona verificada con 15 años de experiencia',
      verified: true,
    },
    description: 'Hermosa habitación privada completamente amueblada en zona segura del barrio norte. Ideal para estudiantes de Tecno.',
    features: {
      privateWc: true,
      furnished: true,
      wifi: true,
      kitchen: true,
      washer: false,
      airCondition: true,
    },
    studentsOnly: true,
    distance: 450,
  },
  {
    id: '2',
    title: 'Cuarto compartido moderno',
    location: 'Centro, 650m del campus',
    price: 320,
    image: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=500&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1567016376408-0226e4d0c1ea?w=800&h=600&fit=crop',
    ],
    type: 'shared',
    amenities: ['Baño compartido', 'WiFi', 'Cocina', 'Lavadora'],
    badges: ['Verified', 'Opción económica'],
    verified: true,
    host: {
      id: 'h2',
      name: 'Carlos Mendez',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
      bio: 'Anfitrión confiable, propietario desde 2018',
      verified: true,
    },
    description: 'Comparte habitación con máximo un estudiante más. Ambiente tranquilo y seguro.',
    features: {
      privateWc: false,
      furnished: true,
      wifi: true,
      kitchen: true,
      washer: true,
      airCondition: false,
    },
    studentsOnly: true,
    distance: 650,
  },
  {
    id: '3',
    title: 'Estudio lujoso completamente amueblado',
    location: 'Zona Premium, 800m del campus',
    price: 750,
    image: 'https://images.unsplash.com/photo-1512895852202-6f4ee016583e?w=500&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1512895852202-6f4ee016583e?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop',
    ],
    type: 'private',
    amenities: ['Baño privado', 'WiFi ultra rápido', 'Cocina equipada', 'Aire acondicionado', 'Lavadora'],
    badges: ['Verificado', 'Premium'],
    verified: true,
    host: {
      id: 'h3',
      name: 'Ana García',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
      bio: 'Propietaria de lujo, garantiza máxima comodidad',
      verified: true,
    },
    description: 'Estudio moderno con todos los lujos. Perfecto para estudiantes con presupuesto mayor.',
    features: {
      privateWc: true,
      furnished: true,
      wifi: true,
      kitchen: true,
      washer: true,
      airCondition: true,
    },
    studentsOnly: false,
    distance: 800,
  },
  {
    id: '4',
    title: 'Habitación con vista al campus',
    location: 'Avenida Universitaria, 300m del campus',
    price: 332,
    image: 'https://images.unsplash.com/photo-1516455207990-7a41e1d4ffd5?w=500&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1516455207990-7a41e1d4ffd5?w=800&h=600&fit=crop',
    ],
    type: 'private',
    amenities: ['Baño privado', 'WiFi', 'Cocina', 'Terraza'],
    badges: ['Verificado', 'Ubicación estratégica'],
    verified: true,
    host: {
      id: 'h4',
      name: 'Pedro López',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
      bio: 'Estudiante antiguo que alquila su casa',
      verified: false,
    },
    description: 'Tienes vista directa al campus desde tu ventana. Excelente ubicación para estudiantes nuevos.',
    features: {
      privateWc: true,
      furnished: false,
      wifi: true,
      kitchen: true,
      washer: false,
      airCondition: false,
    },
    studentsOnly: true,
    distance: 300,
  },
  {
    id: '5',
    title: 'Cuarto acogedor para dos personas',
    location: 'Barrio Sur, 1km del campus',
    price: 220,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=500&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
    ],
    type: 'shared',
    amenities: ['Baño compartido', 'WiFi', 'Cocina compartida'],
    badges: ['Verificado', 'Económico'],
    verified: true,
    host: {
      id: 'h5',
      name: 'Laura Fernández',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
      bio: 'Madre anfitriona, ambiente familiar',
      verified: true,
    },
    description: 'Perfecto para dos amigos que quieren compartir. Ambiente seguro y familiar.',
    features: {
      privateWc: false,
      furnished: true,
      wifi: true,
      kitchen: true,
      washer: true,
      airCondition: false,
    },
    studentsOnly: true,
    distance: 1000,
  },
  {
    id: '6',
    title: 'Apartamento full con terraza',
    location: 'Zona Ejecutiva, 900m del campus',
    price: 380,
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
    ],
    type: 'private',
    amenities: ['Baño privado', 'WiFi', 'Cocina equipada', 'Aire acondicionado', 'Terraza privada', 'Estacionamiento'],
    badges: ['Verificado', 'Premium', 'Cerca del campus'],
    verified: true,
    host: {
      id: 'h6',
      name: 'Javier Romero',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
      bio: 'Propietario profesional con múltiples inmuebles',
      verified: true,
    },
    description: 'Apartamento de lujo con todos los servicios. Ideal para un estudiante que busca comodidad total.',
    features: {
      privateWc: true,
      furnished: true,
      wifi: true,
      kitchen: true,
      washer: true,
      airCondition: true,
    },
    studentsOnly: false,
    distance: 900,
  },
  {
    id: '7',
    title: 'Habitación en casa de familia',
    location: 'Barrio Residencial, 1.2km del campus',
    price: 200,
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=500&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop',
    ],
    type: 'shared',
    amenities: ['Baño compartido', 'Cocina familiar', 'WiFi', 'Comida incluida'],
    badges: ['Verificado', 'Ambiente familiar'],
    verified: true,
    host: {
      id: 'h7',
      name: 'Doña Rosa',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
      bio: 'Anfitriona cálida que trata a los estudiantes como familia',
      verified: true,
    },
    description: 'Vive en una casa acogedora. La dueña ofrece comida casera y cuidado maternal.',
    features: {
      privateWc: false,
      furnished: true,
      wifi: true,
      kitchen: false,
      washer: true,
      airCondition: false,
    },
    studentsOnly: true,
    distance: 1200,
  },
  {
    id: '8',
    title: 'Monoambiente moderno y luminoso',
    location: 'Centro Nuevo, 700m del campus',
    price: 35,
    image: 'https://images.unsplash.com/photo-1512895852202-6f4ee016583e?w=500&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1512895852202-6f4ee016583e?w=800&h=600&fit=crop',
    ],
    type: 'private',
    amenities: ['Baño privado', 'WiFi', 'Cocina completa', 'Luz natural'],
    badges: ['Verificado', 'Moderno'],
    verified: true,
    host: {
      id: 'h8',
      name: 'Sofía Martínez',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
      bio: 'Diseñadora de interiores que renta su proyecto',
      verified: true,
    },
    description: 'Monoambiente diseñado con buen gusto. Espacio pequeño pero muy eficiente.',
    features: {
      privateWc: true,
      furnished: true,
      wifi: true,
      kitchen: true,
      washer: false,
      airCondition: true,
    },
    studentsOnly: true,
    distance: 700,
  },
];

export const FAQ: FAQItem[] = [
  {
    id: '1',
    question: '¿Solo estudiantes del Tecno pueden registrarse?',
    answer: 'Sí, nuestro servicio está diseñado específicamente para estudiantes del Instituto Tecnológico. Requieres una credencial válida para verificar tu identidad como estudiante activo.',
  },
  {
    id: '2',
    question: '¿Cómo se valida la credencial estudiantil?',
    answer: 'Al registrarte, debes cargar una foto clara de tu carnet estudiantil. Nuestro equipo revisa las credenciales dentro de 24-48 horas. Solo aceptamos carnés vigentes del Tecno.',
  },
  {
    id: '3',
    question: '¿Qué sucede si intento falsificar mi identidad?',
    answer: 'La falsedad de identidad es tomada en serio. Los usuarios que intenten falsificar su identidad serán permanentemente baneados de la plataforma y se reportará a las autoridades universitarias.',
  },
  {
    id: '4',
    question: '¿Cómo funciona el proceso de reserva?',
    answer: 'Selecciona una habitación, contáctate con el anfitrión a través de la plataforma, acuerda los términos y realiza el pago. Todos nuestros pagos son seguros y procesados a través de proveedores verificados.',
  },
  {
    id: '5',
    question: '¿Hay comisión en las transacciones?',
    answer: 'Tecno Living cobra una comisión del 5% sobre cada reserva exitosa. Esta comisión cubre los costos de operación y mantenimiento de la plataforma.',
  },
  {
    id: '6',
    question: '¿Qué pasa si tengo un problema con el anfitrión?',
    answer: 'Contamos con un equipo de atención al cliente 24/7. Puedes reportar cualquier problema a través de tu panel. Mediaremos en disputas y, en caso de incumplimiento grave, aplicaremos sanciones.',
  },
  {
    id: '7',
    question: '¿Puedo cambiar de habitación durante mi contrato?',
    answer: 'Depende de los términos específicos de tu contrato con el anfitrión. Recomendamos discutir esta posibilidad antes de confirmar la reserva. La plataforma puede facilitar cambios si ambas partes están de acuerdo.',
  },
  {
    id: '8',
    question: '¿Hay garantía de seguridad en la plataforma?',
    answer: 'Todos nuestros anfitriones pasan verificación de antecedentes. Los pagos son seguros mediante encriptación SSL. Recomendamos visitars las habitaciones antes de reservar y confiar en tu instinto.',
  },
];

export const AMENITIES = [
  'Baño privado',
  'Baño compartido',
  'WiFi',
  'Cocina completa',
  'Cocina compartida',
  'Lavadora',
  'Aire acondicionado',
  'Terraza',
  'Balcón',
  'Parqueo',
  'Amueblado',
];
